haptools_dir:          /home/pedge/git/HapTools
hapcut2:               /home/pedge/git/hapcut2/build/HAPCUT2
data_dir:              /oasis/tscc/scratch/pedge/sissor_project/data
experiments_dir:       /oasis/tscc/scratch/pedge/sissor_project/experiments
error_rates_dir:       /oasis/tscc/scratch/pedge/sissor_project/error_rates
plots_dir:             /oasis/tscc/scratch/pedge/sissor_project/plots
qsub_stdout_dir:       /oasis/tscc/scratch/pedge/sissor_project/stdout
PGP_21_vcfs_old:       /oasis/tscc/scratch/wkchu/SISSOR/PGP1_21_highoutputmem/vcf
PGP_21_pileups_old:    /oasis/tscc/scratch/wkchu/SISSOR/PGP1_21_highoutputmem/pileup
PGP_21_boundaries_old: /oasis/tscc/scratch/wkchu/SISSOR/PGP1_21_highoutputmem/fragmentboundarybed
PGP_22_old:            /oasis/tscc/scratch/wkchu/SISSOR/PGP1_22_highoutput
BAC_hapblocks:         /oasis/tscc/scratch/wkchu/HaplotypeBAC
variant_vcf_dir:       /oasis/tscc/scratch/pedge/sissor/PGP1_VCFs

cell_ids:
    - PGP1_21
    - PGP1_22

input_filetypes:
    - vcf
    - pileup
    - bed
